console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("girar: izquierda");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
console.log("mover: 1, vaciar: 1");
